In [1]:
import pandas as pd

In [ ]:
import requests
from config import API_KEY

url = "https://imdb236.p.rapidapi.com/api/imdb/top250-movies"

headers = {
	"x-rapidapi-key": API_KEY,
	"x-rapidapi-host": "imdb236.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())

[{'id': 'tt0111161', 'url': 'https://www.imdb.com/title/tt0111161/', 'primaryTitle': 'The Shawshank Redemption', 'originalTitle': 'The Shawshank Redemption', 'type': 'movie', 'description': 'A wrongfully convicted banker forms a close friendship with a hardened convict over a quarter century while retaining his humanity through simple acts of compassion.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=xyXX8LXiNJ4', 'contentRating': 'R', 'startYear': 1994, 'endYear': None, 'releaseDate': '1994-10-14', 'interests': ['Epic', 'Period Drama', 'Prison Drama', 'Psychological Drama', 'Drama'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.facebook.com/shawshankredemptionfilm/', 'https://www.warnerbros.com/movies/shawshank-redemption'], 'spokenLanguages': ['en'], 'filmingLocations': ['Butler, Ohio, USA'], 'productionCompanies': [{'id': 'co0040620', 'name': 'Castle Rock Entertainment'}], 'budget': 25000000, 'grossWorldwide': 29423730, 'genres': ['Drama'], 'isAdult': False, 'runtimeMinutes': 142, 'averageRating': 9.3, 'numVotes': 3199484, 'metascore': 82}, {'id': 'tt0068646', 'url': 'https://www.imdb.com/title/tt0068646/', 'primaryTitle': 'The Godfather', 'originalTitle': 'The Godfather', 'type': 'movie', 'description': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=8V2k2YQEQJ4', 'contentRating': 'R', 'startYear': 1972, 'endYear': None, 'releaseDate': '1972-03-24', 'interests': ['Epic', 'Gangster', 'Psychological Drama', 'Tragedy', 'Crime', 'Drama'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.facebook.com/thegodfather/', 'https://www.instagram.com/thegodfathermovie/'], 'spokenLanguages': ['en', 'it', 'la'], 'filmingLocations': ["Forza d'Agrò, Messina, Sicily, Italy"], 'productionCompanies': [{'id': 'co0023400', 'name': 'Paramount Pictures'}, {'id': 'co0921482', 'name': 'Albert S. Ruddy Productions'}, {'id': 'co0255097', 'name': 'Alfran Productions'}], 'budget': 6000000, 'grossWorldwide': 250933053, 'genres': ['Crime', 'Drama'], 'isAdult': False, 'runtimeMinutes': 175, 'averageRating': 9.2, 'numVotes': 2232283, 'metascore': 100}, {'id': 'tt0468569', 'url': 'https://www.imdb.com/title/tt0468569/', 'primaryTitle': 'The Dark Knight', 'originalTitle': 'The Dark Knight', 'type': 'movie', 'description': 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=kmJLuwP3MbY', 'contentRating': 'PG-13', 'startYear': 2008, 'endYear': None, 'releaseDate': '2008-07-18', 'interests': ['DC', 'Action Epic', 'Epic', 'Psychological Drama', 'Psychological Thriller', 'Superhero', 'Crime', 'Thriller'], 'countriesOfOrigin': ['US', 'GB'], 'externalLinks': ['https://www.facebook.com/darkknighttrilogy/', 'https://www.warnerbros.co.uk/movies/dark-knight'], 'spokenLanguages': ['en'], 'filmingLocations': ['Chicago, Illinois, USA'], 'productionCompanies': [{'id': 'co0002663', 'name': 'Warner Bros.'}, {'id': 'co1041831', 'name': 'Legendary Pictures'}, {'id': 'co0038332', 'name': 'DC Comics'}], 'budget': 185000000, 'grossWorldwide': 1008480203, 'genres': ['Crime', 'Thriller'], 'isAdult': False, 'runtimeMinutes': 152, 'averageRating': 9.1, 'numVotes': 3180278, 'metascore': 85}, {'id': 'tt0071562', 'url': 'https://www.imdb.com/title/tt0071562/', 'primaryTitle': 'The Godfather Part II', 'originalTitle': 'The Godfather Part II', 'type': 'movie', 'description': 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=9O1Iy9od7-A', 'contentRating': 'R', 'startYear': 1974, 'endYear': None, 'releaseDate': '1974-12-18', 'interests': ['Epic', 'Gangster', 'Tragedy', 'Crime', 'Drama'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.facebook.com/thegodfather/', 'https://www.instagram.com/thegodfathermovie/'], 'spokenLanguages': ['en', 'it', 'es', 'la'], 'filmingLocations': ['Kaiser Estate - 4000 W Lake Blvd, Homewood, Lake Tahoe, California, USA'], 'productionCompanies': [{'id': 'co0023400', 'name': 'Paramount Pictures'}, {'id': 'co0099634', 'name': 'The Coppola Company'}, {'id': 'co0020958', 'name': 'American Zoetrope'}], 'budget': 13000000, 'grossWorldwide': 48209545, 'genres': ['Crime', 'Drama'], 'isAdult': False, 'runtimeMinutes': 202, 'averageRating': 9, 'numVotes': 1498245, 'metascore': 90}, {'id': 'tt0050083', 'url': 'https://www.imdb.com/title/tt0050083/', 'primaryTitle': '12 Angry Men', 'originalTitle': '12 Angry Men', 'type': 'movie', 'description': 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=TEN-2uTi2c0', 'contentRating': 'Approved', 'startYear': 1957, 'endYear': None, 'releaseDate': '1957-04-10', 'interests': ['Legal Drama', 'Psychological Drama', 'Crime', 'Drama'], 'countriesOfOrigin': ['US'], 'externalLinks': [], 'spokenLanguages': ['en'], 'filmingLocations': ['New York County Courthouse - 60 Centre Street, New York City, New York, USA'], 'productionCompanies': [{'id': 'co0032902', 'name': 'Orion-Nova Productions'}], 'budget': 350000, 'grossWorldwide': 13168, 'genres': ['Crime', 'Drama'], 'isAdult': False, 'runtimeMinutes': 96, 'averageRating': 9, 'numVotes': 987818, 'metascore': 97}, {'id': 'tt0167260', 'url': 'https://www.imdb.com/title/tt0167260/', 'primaryTitle': 'The Lord of the Rings: The Return of the King', 'originalTitle': 'The Lord of the Rings: The Return of the King', 'type': 'movie', 'description': "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=zckJCxYxn1g', 'contentRating': 'PG-13', 'startYear': 2003, 'endYear': None, 'releaseDate': '2003-12-17', 'interests': ['Lord of the Rings', 'Action Epic', 'Adventure Epic', 'Epic', 'Fantasy Epic', 'Mountain Adventure', 'Quest', 'Sword & Sorcery', 'Tragedy', 'Adventure'], 'countriesOfOrigin': ['NZ', 'US'], 'externalLinks': ['https://www.facebook.com/lordoftheringstrilogy', 'http://www.lordoftherings.net/'], 'spokenLanguages': ['en'], 'filmingLocations': ['Hinuera Valley, Matamata, Waikato, New Zealand'], 'productionCompanies': [{'id': 'co0046718', 'name': 'New Line Cinema'}, {'id': 'co0046203', 'name': 'WingNut Films'}, {'id': 'co0061706', 'name': 'The Saul Zaentz Company'}], 'budget': 94000000, 'grossWorldwide': 1149453674, 'genres': ['Adventure', 'Drama', 'Fantasy'], 'isAdult': False, 'runtimeMinutes': 201, 'averageRating': 9, 'numVotes': 2170532, 'metascore': 94}, {'id': 'tt0108052', 'url': 'https://www.imdb.com/title/tt0108052/', 'primaryTitle': "Schindler's List", 'originalTitle': "Schindler's List", 'type': 'movie', 'description': 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=kXYcYhckXD8', 'contentRating': 'R', 'startYear': 1993, 'endYear': None, 'releaseDate': '1994-02-04', 'interests': ['Docudrama', 'Epic', 'Historical Epic', 'Period Drama', 'Prison Drama', 'Psychological Drama', 'Tragedy', 'Biography', 'Drama', 'History'], 'countriesOfOrigin': ['US'], 'externalLinks': ['https://www.facebook.com/SchindlersListMovie/', 'https://www.uphe.com/movies/schindlers-list'], 'spokenLanguages': ['en', 'he', 'de', 'pl', 'la'], 'filmingLocations': ['Auschwitz-Birkenau Concentration Camp, Oswiecim, Malopolskie, Poland'], 'productionCompanies': [{'id': 'co0005073', 'name': 'Universal Pictures'}, {'id': 'co0009119', 'name': 'Amblin Entertainment'}], 'budget': 22000000, 'grossWorldwide': 322161245, 'genres': ['Biography', 'Drama', 'History'], 'isAdult': False, 'runtimeMinutes': 195, 'averageRating': 9, 'numVotes': 1588609, 'metascore': 95}, {'id': 'tt0120737', 'url': 'https://www.imdb.com/title/tt0120737/', 'primaryTitle': 'The Lord of the Rings: The Fellowship of the Ring', 'originalTitle': 'The Lord of the Rings: The Fellowship of the Ring', 'type': 'movie', 'description': 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=_nZdmwHrcnw', 'contentRating': 'PG-13', 'startYear': 2001, 'endYear': None, 'releaseDate': '2001-12-19', 'interests': ['Lord of the Rings', 'Action Epic', 'Adventure Epic', 'Dark Fantasy', 'Epic', 'Fantasy Epic', 'Quest', 'Sword & Sorcery', 'Adventure', 'Drama'], 'countriesOfOrigin': ['NZ', 'US', 'GB'], 'externalLinks': ['https://www.facebook.com/lordoftheringstrilogy', 'https://www.warnerbros.com/movies/lord-rings-fellowship-ring'], 'spokenLanguages': ['en'], 'filmingLocations': ['Wellington, New Zealand'], 'productionCompanies': [{'id': 'co0046718', 'name': 'New Line Cinema'}, {'id': 'co0046203', 'name': 'WingNut Films'}, {'id': 'co0614377', 'name': 'Marzano Films'}], 'budget': 93000000, 'grossWorldwide': 897519866, 'genres': ['Adventure', 'Drama', 'Fantasy'], 'isAdult': False, 'runtimeMinutes': 178, 'averageRating': 8.9, 'numVotes': 2212747, 'metascore': 92}, {'id': 'tt0110912', 'url': 'https://www.imdb.com/title/tt0110912/', 'primaryTitle': 'Pulp Fiction', 'originalTitle': 'Pulp Fiction', 'type': 'movie', 'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=tGpTpVyI_OQ', 'contentRating': 'R', 'startYear': 1994, 'endYear': None, 'releaseDate': '1994-10-14', 'interests': ['Dark Comedy', 'Drug Crime', 'Gangster', 'Crime', 'Drama'], 'countriesOfOrigin': ['US'], 'externalLinks': ['http://www.facebook.com/PulpFiction', 'http://www.miramax.com/movie/pulp-fiction'], 'spokenLanguages': ['en', 'es', 'fr'], 'filmingLocations': ['1435 Flower Street, Glendale, California, USA'], 'productionCompanies': [{'id': 'co0022594', 'name': 'Miramax'}, {'id': 'co0019267', 'name': 'A Band Apart'}, {'id': 'co0010434', 'name': 'Jersey Films'}], 'budget': 8000000, 'grossWorldwide': 213928762, 'genres': ['Crime', 'Drama'], 'isAdult': False, 'runtimeMinutes': 154, 'averageRating': 8.8, 'numVotes': 2442169, 'metascore': 95}, {'id': 'tt0060196', 'url': 'https://www.imdb.com/title/tt0060196/', 'primaryTitle': 'The Good, the Bad and the Ugly', 'originalTitle': 'Il buono, il brutto, il cattivo', 'type': 'movie', 'description': 'A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=3VQjSSB78es', 'contentRating': 'R', 'startYear': 1966, 'endYear': None, 'releaseDate': '1967-12-29', 'interests': ['Action Epic', 'Adventure Epic', 'Dark Comedy', 'Desert Adventure', 'Epic', 'Period Drama', 'Quest', 'Spaghetti Western', 'Western Epic', 'Adventure'], 'countriesOfOrigin': ['IT', 'ES', 'US'], 'externalLinks': [], 'spokenLanguages': ['en', 'it'], 'filmingLocations': ['Cabo de Gata, Almería, Andalucía, Spain'], 'productionCompanies': [{'id': 'co0013844', 'name': 'Produzioni Europee Associate (PEA)'}, {'id': 'co0046114', 'name': 'Arturo González Producciones Cinematográficas'}, {'id': 'co0002257', 'name': 'Constantin Film'}], 'budget': 1200000, 'grossWorldwide': 25280183, 'genres': ['Adventure', 'Drama', 'Western'], 'isAdult': False, 'runtimeMinutes': 178, 'averageRating': 8.8, 'numVotes': 892385, 'metascore': 90}, {'id': 'tt0167261', 'url': 'https://www.imdb.com/title/tt0167261/', 'primaryTitle': 'The Lord of the Rings: The Two Towers', 'originalTitle': 'The Lord of the Rings: The Two Towers', 'type': 'movie', 'description': "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", 'primaryImage': 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@.jpg', 'thumbnails': [{'url': 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_QL75_UX100_CR0,0,100,148_.jpg', 'width': 100, 'height': 148}, {'url': 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_QL75_UX280_CR0,0,280,414_.jpg', 'width': 280, 'height': 414}, {'url': 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', 'width': 380, 'height': 562}], 'trailer': 'https://www.youtube.com/watch?v=nuTU5XcZTLA', 'contentRating': 'PG-13', 'startYear': 2002, 'endYear': None, 'releaseDate': '2002-12-18', 'interests': ['Lord of the Rings', 'Action Epic', 'Adventure Epic', 'Dark Fantasy', 'Epic', 'Fantasy Epic', 'Quest', 'Sword & Sorcery', 'Adventure', 'Drama'], 'countriesOfOrigin': ['NZ', 'US'], 'externalLinks': ['http://www.lordoftherings.net/', 'https://www.facebook.com/lordoftheringstrilogy'], 'spokenLanguages': ['en'], 'filmingLocations': ['Hinuera Valle

In [3]:
df=pd.DataFrame(response.json())[['primaryTitle','originalTitle','type','description','contentRating','interests']]

In [4]:
df.isnull().sum()

primaryTitle     0
originalTitle    0
type             0
description      0
contentRating    6
interests        0
dtype: int64

In [5]:
df.fillna("NaN")

,primaryTitle,originalTitle,type,description,contentRating,interests
0,The Shawshank Redemption,The Shawshank Redemption,movie,A wrongfully convicted banker forms a close fr...,R,"[Epic, Period Drama, Prison Drama, Psychologic..."
1,The Godfather,The Godfather,movie,The aging patriarch of an organized crime dyna...,R,"[Epic, Gangster, Psychological Drama, Tragedy,..."
2,The Dark Knight,The Dark Knight,movie,When a menace known as the Joker wreaks havoc ...,PG-13,"[DC, Action Epic, Epic, Psychological Drama, P..."
3,The Godfather Part II,The Godfather Part II,movie,The early life and career of Vito Corleone in ...,R,"[Epic, Gangster, Tragedy, Crime, Drama]"
4,12 Angry Men,12 Angry Men,movie,The jury in a New York City murder trial is fr...,Approved,"[Legal Drama, Psychological Drama, Crime, Drama]"
...,...,...,...,...,...,...
245,The Passion of Joan of Arc,La passion de Jeanne d'Arc,movie,"In 1431, Jeanne d'Arc is placed on trial on ch...",Passed,"[Costume Drama, Legal Drama, Period Drama, Psy..."
246,Obsession,Obsession,movie,"After breaking the mysterious ""One Wish Willow...",R,"[Dark Romance, Psychological Horror, Psycholog..."
247,The Handmaiden,Ah-ga-ssi,movie,"In 1930s Korea, a girl is hired as a handmaide...",Not Rated,"[Korean, Dark Romance, Erotic Thriller, Psycho..."
248,Drishyam,Drishyam,movie,A man goes to extreme lengths to save his fami...,Not Rated,"[Malayalam, Psychological Thriller, Suspense M..."
249,Gangs of Wasseypur,Gangs of Wasseypur,movie,A clash between Sultan and Shahid Khan leads t...,Not Rated,"[Hindi, Dark Comedy, Gangster, Satire, True Cr..."

In [6]:
df.columns = [
    "movie_title",
    "original_title",
    "type",
    "description",
    "content_rating",
    "genres"
]

In [7]:
df

,movie_title,original_title,type,description,content_rating,genres
0,The Shawshank Redemption,The Shawshank Redemption,movie,A wrongfully convicted banker forms a close fr...,R,"[Epic, Period Drama, Prison Drama, Psychologic..."
1,The Godfather,The Godfather,movie,The aging patriarch of an organized crime dyna...,R,"[Epic, Gangster, Psychological Drama, Tragedy,..."
2,The Dark Knight,The Dark Knight,movie,When a menace known as the Joker wreaks havoc ...,PG-13,"[DC, Action Epic, Epic, Psychological Drama, P..."
3,The Godfather Part II,The Godfather Part II,movie,The early life and career of Vito Corleone in ...,R,"[Epic, Gangster, Tragedy, Crime, Drama]"
4,12 Angry Men,12 Angry Men,movie,The jury in a New York City murder trial is fr...,Approved,"[Legal Drama, Psychological Drama, Crime, Drama]"
...,...,...,...,...,...,...
245,The Passion of Joan of Arc,La passion de Jeanne d'Arc,movie,"In 1431, Jeanne d'Arc is placed on trial on ch...",Passed,"[Costume Drama, Legal Drama, Period Drama, Psy..."
246,Obsession,Obsession,movie,"After breaking the mysterious ""One Wish Willow...",R,"[Dark Romance, Psychological Horror, Psycholog..."
247,The Handmaiden,Ah-ga-ssi,movie,"In 1930s Korea, a girl is hired as a handmaide...",Not Rated,"[Korean, Dark Romance, Erotic Thriller, Psycho..."
248,Drishyam,Drishyam,movie,A man goes to extreme lengths to save his fami...,Not Rated,"[Malayalam, Psychological Thriller, Suspense M..."
249,Gangs of Wasseypur,Gangs of Wasseypur,movie,A clash between Sultan and Shahid Khan leads t...,Not Rated,"[Hindi, Dark Comedy, Gangster, Satire, True Cr..."

In [8]:
df.to_csv("Top_250_IMDB_movies.csv",index=False)